authors = ["Andy Ferris <andy.ferris@roames.com.au>"]
name = "Dictionaries"
uuid = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
version = "0.1.0"

[deps]
Indexing = "313cdc1a-70c2-5d6a-ae34-0150d3930a38"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
SplitApplyCombine = "0.4.1"
Indexing = "1.1"
